### ISSUE TITLE
Custom Function NPM Dependency UI

### ISSUE THREAD

**Issue by patt-ux** [WithOneVisionTechnologies/omnihive-vs-code#2]
As i understand it, currently if you need an NPM dependency not already on the server, you need to add it to the "Account Custom Configurations". You currently can do this 1 of 2 ways:

- Through Super on the machine running Super that is connected to the account you need the dependency on
- By directly adding the entry to the oh_account_custom_configurations table in the database.

Depending on whether the user has access to the OH database or Super may negate the ability to use either of these methods.

I would like to suggest we add a panel/UI/Context Menu to the extension that allows the users to manage any NPM packages that need to be added for their functions. Since we are also driving all custom function coding to happen through the VS Code extension, it will keep the users working with one tool.
When we launch the MDM, this may be obsolete, but for users that prefer working with VSCode or users in the org structure that may not have access to the database directly, this will be a useful feature.

If this already exists - comment how to access the feature and then close out this issue.

Thanks!

**Comment by doug-shontz** [comment]
That's a good call.  MDM won't negate this at all.  In fact, there may be MDM-level things that can be added to the VS Code plugin.

**Comment by doug-shontz** [comment]
Reassigning this to Kaleb so it goes through a better workflow.  This will be added to the PM schedule to help Kaleb know how to prioritize this.  I can see this being important more quickly for OH once people start onboarding.

**Comment by doug-shontz** [comment]
@KalebMatthews has completed this.  I have tested it and it seems to work fine.  Pushing out 2.0.8
